site_name: 'Java Application'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/mankinimbom/webapp
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Java application documentation: 'docs/index.md'
